import type { components } from "@/schemas/schema.d.ts"; // generated by openapi-typescript
import restClient from "../restClient";

// Schema Obj
type Club = components["schemas"]["ClubCardResponse"];
type ClubCreateRequest = components["schemas"]["ClubCreateRequest"];
type ClubCreateResponse = components["schemas"]["ClubCreateResponse"];
type ClubDetailsResponse = components["schemas"]["ClubDetailsResponse"];
type ClubUpdateRequest = components["schemas"]["ClubUpdateRequest"];
type ClubUpdateResponse = components["schemas"]["ClubUpdateResponse"];

export async function getClubs(): Promise<Club[]> {
  return restClient.get<Club[]>("/clubs?page=0&size=100&sort=clubId");
}

export const postClubs = async (
  clubData: ClubCreateRequest,
): Promise<ClubCreateResponse> => {
  return restClient.post<ClubCreateResponse>(
    "/clubs",
    JSON.stringify(clubData),
  );
};

export const postClubsImg = async (clubImg: FormData): Promise<string> => {
  return restClient.postImage<string>("/clubs/images", clubImg);
};

export const getClubsById = async (
  clubId: number,
): Promise<ClubDetailsResponse> => {
  return restClient.get<ClubDetailsResponse>(`/clubs/${clubId}`);
};

export const patchClubs = async (
  clubUpdateData: ClubUpdateRequest,
  clubId: number,
): Promise<ClubUpdateResponse> => {
  return restClient.patch<ClubUpdateResponse>(
    `/clubs/${clubId}`,
    JSON.stringify(clubUpdateData),
  );
};
