import type { components } from "@/schemas/schema.d.ts"; // generated by openapi-typescript

export type GetClubListResponse =
  components["schemas"]["CommonResponsePageClubCardResponse"];
export type PostClubRequest = components["schemas"]["ClubCreateRequest"];
export type PostClubResponse =
  components["schemas"]["CommonResponseClubCreateResponse"];
export type GetClubDetailsResponse =
  components["schemas"]["CommonResponseClubDetailsResponse"];
export type PatchClubRequest = components["schemas"]["ClubUpdateRequest"];
export type PatchClubResponse =
  components["schemas"]["CommonResponseClubUpdateResponse"];
