import type { Metadata } from 'next';
import { UserStateProps } from '@/types/layoutTypes';
import localFont from 'next/font/local';
import './globals.css';
import Header from '@/components/ui/Header';

const geistSans = localFont({
  src: './fonts/GeistVF.woff',
  variable: '--font-geist-sans',
  weight: '100 900',
});
const geistMono = localFont({
  src: './fonts/GeistMonoVF.woff',
  variable: '--font-geist-mono',
  weight: '100 900',
});

export const metadata: Metadata = {
  title: '배드민턴칠까?',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
  isLogin,
  isJoined,
}: UserStateProps & { children: React.ReactNode }) {
  return (
    <html lang="kr">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased w-full flex flex-col justify-start items-center min-h-screen`}
      >
        <div className="w-full max-w-5xl">
          <Header isLogin={isLogin} isJoined={isJoined} />
          {children}
        </div>
      </body>
    </html>
  );
}
